name: Build containers and rebuild azure

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: azure/docker-login@v1
      with:
        login-server: index.docker.io
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
    - run: |
        docker build . -t wlepich/ebiznes-backend:${{ github.sha }} -f Dockerfile.backend
        docker push wlepich/ebiznes-backend:${{ github.sha }}  
        docker build . -t wlepich/ebiznes-frontend:${{ github.sha }} -f Dockerfile.frontend
        docker push wlepich/ebiznes-frontend:${{ github.sha }}
