name: Build containers and rebuild azure

on: [ push ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check Out Repo
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_TOKEN }}

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push base image
        id: docker_build_base
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile.base
          push: true
          tags: ${{ secrets.REGISTRY_USERNAME }}/ebiznes-base:latest
          cache-from: type=registry,ref=user/app:latest
          cache-to: type=inline

      - name: Build and push backend image
        id: docker_build_backend
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile.backend
          push: true
          tags: ${{ secrets.REGISTRY_USERNAME }}/ebiznes-backend:latest
          cache-from: type=registry,ref=user/app:latest
          cache-to: type=inline

      - name: Build and push frontend image
        id: docker_build_frontend
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile.frontend
          push: true
          tags: ${{ secrets.REGISTRY_USERNAME }}/ebiznes-frontend:latest
          cache-from: type=registry,ref=user/app:latest
          cache-to: type=inline

